Repository UBC-MDS/DSCI-532_2024_14_mds_saves_america, pull requests merged in 2024-04, with the labels that each got.

#50 49 add numerical age column
  data/processed/data_cleaned.csv
  notebooks/Data_preprocessing_engineering.ipynb
  reports/m1_proposal.md
Labels: enhancement

#51 Add the age range slider
  src/app.py
Labels: good first issue

#55 45 edit the readme file zth96 areyh
  README.md
Labels: documentation

#59 removed dependencies incompatible with windows and added altair vega-…
  environment.yml
Labels: bug

#62 61 final touches to readme
  LICENSE.md
  README.md
Labels: documentation

#63 42 reflection document sampsonyu salva u areyh zth96
  reports/m2-reflection.md
Labels: documentation

#75 74 heatmap instead of table
  src/app.py
  src/callbacks.py
  src/components.py
Labels: enhancement

#77 76 fix the chart components fit to one page
  src/app.py
  src/assets/style.css
  src/callbacks.py
  src/components.py
  src/css/style.css
Labels: enhancement

#89 Improvements on Political Party by Race Stacked Bar Chart
  src/components.py
Labels: enhancement

#90 Improvement on Political Party by Education Level Stacked Bar Chart
  src/components.py
Labels: enhancement

#91 Improvement on Donut Chart
  src/components.py
Labels: enhancement

#92 Improvement on horizontal bar chart perceived likelihood of war
  src/components.py
Labels: enhancement

#98 reflection doc added with current enhancements
  reports/m3-reflection.md
Labels: documentation

#110 108 fix the data preprocessing dkref column zth96
  data/processed/data_cleaned.csv
  notebooks/Data_preprocessing_engineering.ipynb
Labels: enhancement

#111 107 refine UI
  src/app.py
  src/components.py
Labels: enhancement

#120 119 data source using parquet
  data/processed/data_cleaned.csv
  data/processed/data_cleaned.parquet
  data/processed/pulseofthenation.csv
  environment.yml
  notebooks/Data_preprocessing_engineering.ipynb
  notebooks/processing.ipynb
  requirements.txt
  src/app.py
  src/data.py
Labels: enhancement

#124 123 make sure that color means the same thing everywhere or make it really clear if it doesnt
  src/app.py
  src/components.py
Labels: documentation, enhancement

#125 112 remove axis title for two stacked bar charts
  src/components.py
Labels: enhancement

#127 114 Removed y-axis decimal point on by Race stacked bar chart
  src/components.py
Labels: enhancement

#128 115 Disabled legend click function in education level stacked bar chart
  src/components.py
Labels: enhancement

#126 113 Add back y-axis and keep no decimal point
  src/components.py
Labels: enhancement

#134 Added the favicon
  src/app.py
  src/assets/favicon.ico
Labels: enhancement

#137 added reflection
  reports/m4-reflection.md
Labels: documentation

#135 added the message div to display when 0 selections are made
  src/app.py
Labels: enhancement

#140 138 use caching for at least one function
  README.md
  environment.yml
  img/demo_milestone4.gif
  requirements.txt
  src/app.py
  src/cache_config.py
  src/callbacks.py
  src/components.py
Labels: enhancement
